services:

  app:
    build: .
    container_name: lifevault-app
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mysql:8.4
    platform: linux/amd64
    container_name: lifevault-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lifevault
    ports:
      - "3307:3306"
    volumes:
      - lifevault-db-data:/var/lib/mysql

volumes:
  lifevault-db-data: